language: node_js
node_js:
  - "node"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
- npm update

install:
  - npm install

services:
  - postgresql

before_script:
  - npm run buildtest
  - psql postgres://salesforcetester:test@localhost:5432/salesforcetest CREATE SCHEMA salesforce; SET search_path TO salesforce, public;
script:
  - npm test